### ISSUE TITLE
Abril 17 Team CodeReview

### ISSUE THREAD

**Issue by FrancoRosa** [Jmagero/newsweek-clone#1]

**Comment by SevlaMare** [comment]
![123](https://user-images.githubusercontent.com/40220867/79580084-e0078a00-809e-11ea-9469-db7f3f4b9160.png)

The overflow can be solved reducing the margins between the links, like in the original.

**Comment by FrancoRosa** [comment]
# Great progress on your solo project
```
body{
  width: 80%;
  margin: 0 auto;
  font-family: "Roboto Condensed", sans-serif;
}
```
The 80% With may create some issues when resizing, instead you can use **max-width** to restrict the size on large screens.

You can use bootstrap to change margins with **m-0**  **m-auto**
https://getbootstrap.com/docs/4.4/layout/utilities-for-layout/#margin-and-padding

**Comment by idgm5** [comment]
As @SevlaMare commented.

Just reduce nav-link padding to 0.5rem

```
.nav-link {
    display: block;
    padding: .5rem 0.5rem;
}
```
Also delete justify-content-around class. No need for the top bar menu.

I suggest you make your breakpoint to hide the sub-menu at 998px or less than 1000px

**Comment by Jmagero** [comment]
closed
