### ISSUE TITLE
April 22 Code Review

### ISSUE THREAD

**Issue by ferbaco86** [Jmagero/newsweek-clone#2]

**Comment by ferbaco86** [comment]
When resizing below 576px the navbar comes back to the original desktop size: 

![Captura de Pantalla 2020-04-22 a la(s) 10 21 16](https://user-images.githubusercontent.com/52765379/79993748-179d7a00-8483-11ea-996e-23931e9bd710.png)

**Comment by harshdeepkanhai** [comment]
https://chris.beams.io/posts/git-commit/ 
Git headings should be in imperative style and follow the guidelines

**Comment by Jmagero** [comment]
resolved
